### PR TITLE
Replace the unmanaged oracle drivers with the managed drivers

### PR DESCRIPTION
**Pull request by Angela-AM**
Replace the unmanaged oracle drivers with the managed drivers. Making build create the nugget and change the configuration to AnyCPU.

### CODE REVIEW

**Comment by mathijs-dumon** [comment]
This is also a prerequisite for #3

**Comment by airbreather** [comment]
@FObermaier or @DGuidi, do you have something set up to run integration tests on this library against a real Oracle database?

I don't see anything obviously wrong with this change, but I don't feel comfortable swapping out the underlying provider implementation without a decent way to see it working beyond what our automated tests are currently set up to cover.

**Comment by FObermaier** [comment]
No, I don't have any hands-on experience with Oracle database servers.

**Comment by DGuidi** [comment]
same for me :( no way to test agains an actual oracle server...

**Comment by mathijs-dumon** [comment]
Hi all,

We have a development oracle server we can test against. We could perhaps
create a schema to test a client against. Providing you direct access will
not be possible though.

Cheers,
Mathijs

Op do 18 nov. 2021 16:14 schreef Diego Guidi ***@***.***>:

**Comment by FObermaier** [comment]
A docker container with some free/community edition?
The PostGIS project has that.

**Comment by mathijs-dumon** [comment]
some time has passed and we have been able to work on this - we actually have an integration test ready which connects to a docker image with Oracle XE. It reads and writes geometries fine.

However, we've run into an issue on our 'real' code because the SDO geometry type uses decimal's instead of double. This causes overflow exceptions when converting from the NetTopologySuite geometries. We can obviously change the decimals in SdoGeometry.cs to doubles, but I'm not sure this is correct.

Anyone here has some insight in this? Was it a conscious decision to use decimal instead of double?

**Comment by FObermaier** [comment]
I assume that the SdoGeometry et. al. code came directly from the samples mentioned in 
https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/udt-related-classes.html

**Comment by mathijs-dumon** [comment]
Hm ok - than probably we can change this
I just found this more recent set of examples (linked in the blog post announcing support for UDT in the managed driver)
https://github.com/oracle/dotnet-db-samples/blob/master/samples/udt/Spatial-UDT.cs

there, they are using double's

we'll update this in our repo so the PR will reflect this and we should also be able to finish the container example with readme in the coming 2 weeks

**Comment by FObermaier** [comment]
> we'll update this in our repo so the PR will reflect this and we should also be able to finish the container example with readme in the coming 2 weeks

I think this is the way to go. Thanks

**Comment by mathijs-dumon** [comment]
Hi!

So we managed to wrap this one up.
We also changed the datatypes from decimal to double where appropriate.

In the test project there is a README with instructions on how to set up a docker image & run the tests against that empty database.

Seems to work fine for me, I hope this suffices, let us know if not.

**Comment by FObermaier** [comment]
Thanks a lot for your contribution!

**Pull request merged**
